sudo: required
services:
  - docker

before_install:
  - docker build -t fmod31/react-test -f ./client/Dockerfile.env ./client

script:
  - docker run fmod31/react-test npm run test -- --coverage

after_success:
  - docker build -t fmod31/multi-client ./client
  - docker build -t fmod31/multi-nginx ./nginx
  - docker build -t fmod31/multi-server ./server
  - docker build -t fmod31/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push fmod31/multi-client
  - docker push fmod31/multi-nginx
  - docker push fmod31/multi-server
  - docker push fmod31/multi-worker